# Generated by Django 4.1 on 2022-09-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geral', '0002_autor_rename_conteude_pagina_conteudo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagina',
            name='imagem',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(max_length=40),
        ),
    ]
